### ISSUE TITLE
Selecting any option in Audio Settings on the Pause Menu crashes IKEMEN

### ISSUE THREAD

**Issue by Hexioum** [Windblade-GR01/Ikemen-GO#392]
How to replicate:
Add
```
menu.itemname.menuaudio = "Audio Settings"
menu.itemname.menuaudio.mastervolume = "Master Volume"
menu.itemname.menuaudio.bgmvolume = "BGM Volume"
menu.itemname.menuaudio.sfxvolume = "SFX Volume"
menu.itemname.menuaudio.empty = ""
menu.itemname.menuaudio.back = "Back"
```
below **[Menu Info]**

Then pause in-game, and select any of the options (except back)
It doesn't show the percentage of the volume either.

![image](https://user-images.githubusercontent.com/36753605/141939921-3e188f48-9add-4ce9-982f-a1f91838f9a3.png)

**Comment by K4thos** [comment]
fixed, thanks. Not a new problem so I assume up to this point no one else tried to render option screen settings with values (on the right side of setting name) on pause menu.

**Comment by Hexioum** [comment]
Great! Just got the files from the commit and now it displays the volume percentage properly.
I can't change the value (by tapping left or right) though and it still crashes when selecting any of these options.
Maybe I'm missing something.
![image](https://user-images.githubusercontent.com/36753605/142020432-5ec81cc9-14cb-440d-8ce5-fd44c8e8255b.png)

**Comment by K4thos** [comment]
after checking the code it turned out that you are not supposed to use option screen settings in pause menu - there is no logic to handle it there. List of available options is on wiki: https://github.com/K4thos/Ikemen_GO/wiki/Screenpack-features/#submenus
Need to think about it but I will probably revert that previous commit since this was not a problem after all.

**Comment by K4thos** [comment]
I've added support for option screen settings for pause menu in above commit. For the on the fly bgm volume update you will have to wait for 0.98.2 since that change is in source code (currently bgm volume change works only for the next song).

**Comment by Hexioum** [comment]
Thank you, it works fine now.
